### ISSUE TITLE
How to access twill admin?

### ISSUE THREAD

**Issue by MauricioKruijer** [Codivores/tutorial-laravel-twill-inertia-vue3-vite-tailwind#1]
Hi there! Great work on this tutorial!

I am using valet and have linked two domains to this folder, edited my .env with proper url's but I don't seem to be able to get into the twill admin/management system.

#### Steps to reproduce
- checkout this repo, install deps
- `valet link tutorial-twill-inetria`
- `valet link admin.tutorial-twill-inetria`
- update .env with the following variables
```
APP_URL=tutorial-twill-inetria.test
ADMIN_APP_URL=admin.tutorial-twill-inetria.test
SESSION_DOMAIN=.tutorial-twill-inetria.test
MEDIA_LIBRARY_ENDPOINT_TYPE=local
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Glide
S3_KEY=S3_KEY
S3_SECRET=S3_SECRET
S3_BUCKET=bucket-name
IMGIX_SOURCE_HOST=source.imgix.net
```
- navigate to http://admin.tutorial-twill-inetria.test/

#### Expected behaviour
Twill login screen

#### Actual behaviour
Twill site (vue app rendered by inertia)

Am I doing something wrong or did is miss a step?

**Comment by futurewebsites** [comment]
/administration is the admin url but I get an AWS error

**Comment by futurewebsites** [comment]
`Aws\Exception\CredentialsException
Error retrieving credentials from the instance profile metadata service. (cURL error 7: Failed to connect to 169.254.169.254 port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/) (View: /var/www/html/vendor/area17/twill/views/layouts/listing.blade.php)`

I have no Idea why I am getting this as far as I can see its not even using AWS ?

**Comment by MauricioKruijer** [comment]
> ... 
> I have no Idea why I am getting this as far as I can see its not even using AWS ?

I had the same error. Try to use the same S3_ env vars as I have listed, even tough you don't use AWS at this point you still need it in your .env (not sure if this is considered a bug tho)

**Comment by tdn-p** [comment]
Because the config\twill.php default media/file library point to s3. Just add .env as below:

MEDIA_LIBRARY_ENDPOINT_TYPE=local
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Glide

FILE_LIBRARY_ENDPOINT_TYPE=local
FILE_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\FileLibrary\Disk

**Comment by tech-codivores** [comment]
Hi @MauricioKruijer, @futurewebsites, @tdn-p,
really sorry, we didn't see your issues until today...
The repository was a draft and we didn't take time to work on it for a long time. We made a new branch (main) for the current Laravel 10 and Twill 3 versions and we are updating the articles on https://tech.codivores.com/series/laravel-twill-inertia
(more articles to come for blocks, preview, ...).

Are your issues still active? If not, may we close the issue?

Have a good day

**Comment by tech-codivores** [comment]
I'm closing the issue, but feel free to reopen it if you still have troubles

**Comment by tech-codivores** [comment]
I'm closing the issue, but feel free to reopen it if you still have troubles
